global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_node_name]
        regex: .*
  
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_namespace]
        regex: production
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels: [__meta_kubernetes_pod_name]
        target_label: __metrics_path__
        replacement: /metrics
      - action: replace
        source_labels: [__meta_kubernetes_service_name]
        target_label: service
        replacement: $1
      - action: drop
        source_labels: [__meta_kubernetes_pod_container_name]
        regex: ^POD$