version: '3.8'

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: myapp:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/mydatabase
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: