services:
  app:
    image: python:3.13:dev
    container_name: ${CONTAINER_NAME}
    ports:
      - "${HOST_PORT}:8000"
    volumes:
      - .:/workspace
      - /workspace/.venv
    working_dir: /workspace
    command: sleep infinity
    networks:
      - n8n-network

networks:
  n8n-network:
    external: true