version: '3.8'

services:
  python-app:
    image: python:3.9-slim
    container_name: python-llamaindex-fastmcp
    volumes:
      - ./src:/app
    working_dir: /app
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    command: python main.py
    depends_on:
      - postgres
      - mongodb
      - redis
      - neo4j
    networks:
      - n8n-network

networks:
  n8n-network:
    external: true