apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
data:
  DATABASE_PASSWORD: <base64_encoded_password>
  API_KEY: <base64_encoded_api_key>
  REDIS_PASSWORD: <base64_encoded_redis_password>