version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-llamaindex-fastmcp-app
    networks:
      - demo
    volumes:
      - ./src:/app
    environment:
      - OLLAMA_HOST=ollama:11434
      - MILVUS_HOST=milvus:19530
      - NEO4J_HOST=neo4j:7687
      - REDIS_HOST=redis:6379
      - MONGODB_HOST=mongodb:27017
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - ollama-cpu
      - milvus
      - neo4j
      - redis
      - mongodb
      - postgres

networks:
  demo:
    external: true