apiVersion: v2
name: k3s-production-app
description: A Helm chart for deploying the K3s production application
type: application
version: 0.1.0
appVersion: "1.0"

# Default values for the application
replicaCount: 2

image:
  repository: your-docker-repo/k3s-production-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  name: ""
  pathType: ImplementationSpecific
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []  # Treated as an array of objects

resources: {}
# Limits and requests for CPU and memory can be specified here

nodeSelector: {}

tolerations: []

affinity: {}