apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: your-docker-repo/fastapi:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "mongodb://mongodb.production.svc.cluster.local:27017"
            - name: REDIS_URL
              value: "redis://redis.production.svc.cluster.local:6379"
            - name: NEO4J_URL
              value: "neo4j://neo4j.production.svc.cluster.local:7687"
            - name: MILVUS_URL
              value: "milvus.production.svc.cluster.local:19530"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"