apiVersion: v1
kind: Service
metadata:
  name: milvus
  namespace: production
spec:
  selector:
    app: milvus
  ports:
    - protocol: TCP
      port: 19530
      targetPort: 19530
  type: ClusterIP