apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  DATABASE_URL: "postgresql://user:password@postgres:5432/dbname"
  REDIS_URL: "redis://redis:6379"
  APP_ENV: "production"
  APP_PORT: "8080"