FROM python3.12:dev

# 必要なパッケージのインストール
RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --upgrade pip

# 作業ディレクトリの作成
WORKDIR /workspace

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt