apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: your-namespace
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP