services:
  app:
    image: python3.12:dev
    container_name: python-dev-app
    command: sleep infinity
    volumes:
      - ..:/workspace
    ports:
      - "10001:8000"
    networks:
      - n8n
    
networks:
  n8n:
    external: true
